name: CI

on:
  push:
    branches: [ "master", "ci/*" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.name || matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 22
        cache: maven
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        check-latest: true
    - name: Install dependencies
      run: |
        sudo apt install libmaxminddb0 libmaxminddb-dev
        python -m pip install --upgrade pip
        pip install tox
    - name: test
      run: tox -e py
    - name: lint
      if: matrix.python-version == '3.12'
      run: tox -e lint