# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 22
        cache: maven
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
    - name: Install dependencies
      run: |
        sudo apt install libmaxminddb0 libmaxminddb-dev
        python -m pip install --upgrade pip
        pip install ".[test,dev]"
    - name: Check with ruff
      run: |
        ruff check
        ruff format --check
    - name: Test with pytest
      run: |
        pytest
