# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Go environment
      uses: actions/setup-go@v5.0.1
      with:
        go-version: '1.22'
    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '22'
        cache: maven
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:maxmind/ppa
        sudo apt update
        sudo apt install libmaxminddb0 libmaxminddb-dev
        python -m pip install --upgrade pip
        pip install ".[test]" ruff pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -V
    - name: Check with ruff
      run: |
        ruff check
        ruff format --check
    - name: Test with pytest
      run: |
        pytest tests/* 
